### ISSUE TITLE
Fix API

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#10]
I don't know how the API was getting generated in coala, but we should do it here too.

Actually maybe even not, as we want to do a nice API documentation anyway, so if anyone feels like doing it, we'd love it!

**Comment by Mixih** [comment]
@Adrianzatreanu Is this issue still relevant?

**Comment by Mariatta** [comment]
Hmm... I think we already have API docs..

I'm closing this. Feel free to reopen if you disagree :)
