### ISSUE TITLE
Newcomer issues link in newcomers guide should be `https://docs.coala.io/new`

### ISSUE THREAD

**Issue by chauffer** [coala/documentation#110]
https://github.com/coala/documentation/blob/e2a113921a27fc77ddb47c668e4db5fa20a8a0fc/Getting_Involved/Newcomers.rst

difficulty/newcomer

**Comment by Dawny33** [comment]
The existing link re-directs to the issue page with the following filters: `is:open is:issue user:coala-analyzer label:difficulty/newcomer no:assignee`, which is legit enough.

**Comment by sils1297** [comment]
That filter is wrong because we changed the organization from coala-analyzer to coala. Our own coala.io link shortener has the advantage of us being able to change where they redirect to if something happens so we want to use those exclusively.
