### ISSUE TITLE
Mention in tutorial to add a pic to github

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#114]
It should be mentioned somewhere in the Newcomers' Tutorial that it'd be nice if people could set up a profile picture on Github. Maybe it's just me, but I hate the default ones, and i can't even differentiate people that dont have ones, they all look the same. I think everyone should have a profile pic thats unique to them, it makes them distinguish out from the crowd :)

**Comment by Nosferatul** [comment]
I wanna work on this!

**Comment by Adrianzatreanu** [comment]
this issue is quite easy, but i really want it to happen so lets do it :D
