### ISSUE TITLE
Change sentence in 'Adding coala as a Git Hook'

### ISSUE THREAD

**Issue by ma3lstrom** [coala/documentation#117]
The following sentence structure is incorrect: 
> Using git hooks coala can be executed automatically, ensuring your code follows your quality requirements.

It can be found in Users/coala_as_Git_Hook.html 

difficulty/newcomer

**Comment by souradeeptab** [comment]
Hi,
I would like to work on this issue. I have went ahead and already made the changes and made a pull request regarding the same. This would be my first pull request and hopping to see this one get accepted :)

**Comment by Adrianzatreanu** [comment]
Hey, unfortunately i cannot assign you yet because you are not in our organization. I have sent you an invitation and it can be accepted upon email or on github.com/coala :) please join us on [gitter](https://gitter.im/coala/coala) for more information and an active communtiy :D

**Comment by Adrianzatreanu** [comment]
@souradeeptab you have been assigned as requested :)
