### ISSUE TITLE
Change looses->loses in 'Using Glob Patterns'

### ISSUE THREAD

**Issue by ma3lstrom** [coala/documentation#118]
The sentence:

> Matches any character in seq. Cannot be empty. Any special character looses its special meaning in a set.

Should be changed to:

> Matches any character in seq. Cannot be empty. Any special character loses its special meaning in a set.

Found in Users/Glob_Patterns.html or Using Glob Patterns/Syntax

More instances of loose instead of lose are present. Switch all instances of the word loose in that file. 

difficulty/newcomer

**Comment by achetan40** [comment]
Please assign this issue to me

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by DumAdrian** [comment]
i want to be assigned
