### ISSUE TITLE
"Keeping your fork in sync" link is broken

### ISSUE THREAD

**Issue by Flap-Py** [coala/documentation#124]
In Git_Basics.rst the link to http://coala.readthedocs.org/en/latest/Users/Tutorials/Git_Help.html#keeping-your-fork-in-sync is broken.

**Comment by raghvendrar** [comment]
I want to work on this but what is the correct link?

**Comment by Adrianzatreanu** [comment]
it should point to "#Rebasing" on the same page.

**Comment by Adrianzatreanu** [comment]
it can be done using relative paths in rst.
