### ISSUE TITLE
Developers' Newcomers Guide has a broken link to Writing Bears guide

### ISSUE THREAD

**Issue by athend** [coala/documentation#126]
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html

Step 3 > See also > 

The link needs to be changed to http://coala.readthedocs.io/en/latest/Developers/Writing_Bears.html

File: https://github.com/coala/documentation/blob/e45e9478aac5f776656b81c9a950aa816f3f4180/Developers/Newcomers_Guide.rst

**Comment by raghvendrar** [comment]
I want to work on this.

**Comment by sils1297** [comment]
please change the link to http://coala.io/writingbears instead, assigning you

**Comment by Adrianzatreanu** [comment]
long inactivity,  im closing this in favor of opening an issue that holds all broken links since this is quite urgent. https://github.com/coala/documentation/issues/173
