### ISSUE TITLE
Developers' Newcomers Guide has a broken link to Executing tests

### ISSUE THREAD

**Issue by athend** [coala/documentation#127]
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html

Step 4 > See also >

The link needs to be changed. Existing link http://coala.readthedocs.io/en/latest/Getting_Involved/Testing.html is broken

File: https://github.com/coala/documentation/blob/e45e9478aac5f776656b81c9a950aa816f3f4180/Developers/Newcomers_Guide.rst

**Comment by ventris** [comment]
I'll fix this

**Comment by sils1297** [comment]
Hey, we recommend going for a low issue after fixing a newcomer issue. We only have limited newcomer issues available and they're usually more work for us than fixing them. I'd recommend concentrating on your other issue and then picking up low difficulty tasks.
