### ISSUE TITLE
Developers' Newcomers Guide has a broken link to low issue

### ISSUE THREAD

**Issue by athend** [coala/documentation#129]
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html

Step 7 >

Congratulations! Your PR just got accepted! You’re awesome. Now you should go for a **[low issue](http://coala.readthedocs.io/en/latest/Developers/tinyurl.com/coala-low)**, they are really rewarding!

URL to coala low issue is broken.

File: https://github.com/coala/documentation/blob/e45e9478aac5f776656b81c9a950aa816f3f4180/Developers/Newcomers_Guide.rst

**Comment by ventris** [comment]
I'll fix this

**Comment by sils1297** [comment]
Hey, we recommend going for a low issue after fixing a newcomer issue. We only have limited newcomer issues available and they're usually more work for us than fixing them. I'd recommend concentrating on your other issue and then picking up low difficulty tasks.

**Comment by dip-kush** [comment]
Should I give a PR for this ?

**Comment by srisankethu** [comment]
Hi! Looks like you are new to coala. Join our community at https://gitter.im/coala/coala and also take a look at our newcomers guide to speed things up http://docs.coala.io/en/latest/Developers/Newcomers_Guide.html
