### ISSUE TITLE
Linter_Bears_Advanced: Fix typo

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#140]
https://github.com/coala/documentation/blob/master/Developers/Linter_Bears_Advanced.rst

Inside paragraph:
**Supplying Configuration Files with generate_config**

The code example contains a typo:
```
config_file = ("value1 = 1\n"
                       "value=2 = 2")
```
It shall be `value2 = 2` instead of `value=2 = 2`

**Comment by yash-nisar** [comment]
Can I resolve this or should it be left for the newcomers ?

**Comment by ventris** [comment]
I did it in the wrong order, but you can assign me to this if not yash-nisar is taking it.

**Comment by yash-nisar** [comment]
What do you mean by wrong order ? @ventris

**Comment by ventris** [comment]
I created the pull request before I asked for assignment.

**Comment by Makman2** [comment]
@yash-nisar As this is newcomer I would give this one to @ventris , @yash-nisar you already know how our PRs do work ;)

**Comment by yash-nisar** [comment]
Sure, not a problem @Makman2 .
