### ISSUE TITLE
Developers/Writing_Good_Commits.rst: Should have a tag and and a short description separated by a colon

### ISSUE THREAD

**Issue by Udayan12167** [coala/documentation#151]
"and" is repeated.

**Comment by akashfoss** [comment]
Can anyone assign me for this issue ?

**Comment by anant3110** [comment]
Assign me this issue

**Comment by Akki356** [comment]
please assign me to this issue :)

**Comment by sils** [comment]
@anant3110 still workig on this?

**Comment by anant3110** [comment]
Yes

Anant Sharna
2016129
IIIT Delhi (ECE)

**Comment by sils** [comment]
Unassigning as per own request

**Comment by OctavianGuzu** [comment]
Add me this issue !

**Comment by Makman2** [comment]
@OctavianGuzu you got already one assigned :)

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3257
