### ISSUE TITLE
Developers/Git_Basics.rst : Link to the section "writing good commits" not working.

### ISSUE THREAD

**Issue by rishus23** [coala/documentation#157]
"writing good commits" tag is referenced to "http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html" which is not working.

Should be referenced to "http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html".

**Comment by Adrianzatreanu** [comment]
use coala.io/commit

**Comment by rishus23** [comment]
Yes, Ok.
