### ISSUE TITLE
Developers/Newcomers_Guide.rst: Fix the broken link

### ISSUE THREAD

**Issue by aptrishu** [coala/documentation#168]
In **Step 7 - Review process** 

> You might be wondering what those CI things on your Pull Request are. For more detailed info about them, see :doc:`this page <../Help/FAQ>`.

Link mentioned in this line is broken.

**Comment by aptrishu** [comment]
which page should I refer that link to ?

**Comment by aptrishu** [comment]
I couldnt find any coala doc on CI.

**Comment by Adrianzatreanu** [comment]
since this doesnt have a PR yet, im closing this in favor of opening an issue that holds all broken links since this is quite urgent. https://github.com/coala/documentation/issues/173
