### ISSUE TITLE
Fix all broken links in the documentation

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#173]
Some links went broken due to renaming of fodlers and structure, this issue is meant to fix them

**Comment by Dayfiri** [comment]
Can you assign me ?

**Comment by Adrianzatreanu** [comment]
No, this is quite urgent and wanted as many people encounter those links and I want to do it quite fast so we dont encounter any more problems with newcomers. Sorry!

**Comment by nayangupta824** [comment]
i can do

**Comment by Dayfiri** [comment]
Ok no problem.

**Comment by nayangupta824** [comment]
i made a PR please check

**Comment by Adrianzatreanu** [comment]
I am already working on this, as I'm assigned, sorry for the inconvenience, please work on something unassigned.

**Comment by Dayfiri** [comment]
https://github.com/coala/documentation/pull/167

Here is what I did before.
