### ISSUE TITLE
Newcomers_Guide.rst: Remove double \n

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#182]
There are two empty lines in that file, should be corrected to only a single one.

**Comment by amrandahvur** [comment]
Please Assign me this

**Comment by Makman2** [comment]
@amrandahvur 
As we are running out of `difficulty/newcomer` issues and you've already done one, please consider to take a `difficulty/low` issue, you are mostly aware of our review process :) These issues also involve a bit programming :D

**Comment by amrandahvur** [comment]
@Makman2 Sure, I have a small question though, Do you guys have a guide for issues marked with difficulty/low ? In other words, considering that you guys have a large code base, how do i actually comprehend that and start contributing on lower ones ? Is the documentation sufficient ?

**Comment by amrandahvur** [comment]
Sure, I will try my hands on those :)
