### ISSUE TITLE
Newcomers_Guide.rst: work load -> workload

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#184]
*workload* is a legal word.

**Comment by AdiChat** [comment]
I would like to be assigned this as a part of [picking up an issue](https://github.com/coala/documentation/blob/master/Developers/Newcomers_Guide.rst#step-3-picking-up-an-issue).

**Comment by sils** [comment]
@AdiChat there you go!

**Comment by AdiChat** [comment]
Consider unassigning me this issue. I have understood the workflow and am thinking against documentation PR for some reason. I have been active on GitHub for quite some time and would like to keep this open for newcomers. Hopefully, you will understand my situation. Thanks.

**Comment by Makman2** [comment]
huh but it's completely okay that we merge your PR :O
that's part of the process imo, but okay if you want ...

if you reconsider just write here^^

**Comment by amrandahvur** [comment]
Please assign me this if @AdiChat isnt working on it
