### ISSUE TITLE
Be more forceful about using branches

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#193]
http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#creating-a-new-branch currently says

> To start working on an issue, you first need to create a new branch where you will work.
> 
> ```
> $ git checkout -b branchname
> ```

I think the document should explain why using "master" is a very bad idea, and more importantly include a "make sure you are not using master" check at every step of the process.

Also, it would be helpful to provide examples of useful branch naming schemes instead of `branchname`.  Some common schemes:
- issueXXX
- patchXXX
- gh-XXX

It may also be useful to use "my-first-good-pull-request" as the branch name, as it is the first one which is the most problematic.

Then continue to use that throughout the document, using `git checkout my-first-good-pull-request` at the beginning of each block of example commands, so that our documentation is teaching them what a branch is, and our documentation works even if they have use other git commands they have found on the internet.

**Comment by yash-nisar** [comment]
difficulty/low

**Comment by Cygnus32** [comment]
assign this to me please :)

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3253
