### ISSUE TITLE
document all entry-points 

### ISSUE THREAD

**Issue by abhsag24** [coala/documentation#2]
IMO we should have a small description somewhere in the tutorial,  like we do with `exit_codes`

**Comment by BrateS** [comment]
this is deprecated, should be closed

**Comment by Makman2** [comment]
One or two are deprecated, but we still have some:
https://github.com/coala/coala/blob/master/setup.py#L103

**Comment by jayvdb** [comment]
Do we want these extra entry-points?

If not, then we dont want to document them?

Is there any functionality which can only be accessed by the extra entry-points?
We should create issues in the main repo to ensure everything can be done using `coala`, unless there is a very good reason it should be a separate entry point.

**Comment by Makman2** [comment]
Don't think so right now, so yeah let's rather merge every entrypoint into the main one :+1:

**Comment by Makman2** [comment]
Actually we also have now `--json` and `--format` options :+1: So maybe this issue got invalid anyway^^
