### ISSUE TITLE
pylint option issue on Linter Bears page

### ISSUE THREAD

**Issue by nsgonultas** [coala/documentation#206]
On the page about [Linter Bears](https://docs.coala.io/en/latest/Developers/Writing_Linter_Bears.html), all return statements of `create_argument` functions are wrong.
This is what they look like now:
```
return ('--msg_template="L{line}C{column}: {msg_id} - {msg}"', '--reports=n', filename)
```
But pylint doesn't have an option called `--msg_template`. It must be `--msg-template` instead.
Wrong lines must be corrected like this:
```
return ('--msg-template="L{line}C{column}: ...)
```

**Comment by virresh** [comment]
Hello, I'd like to take up on this issue. I think I can fix it by changing the .rst file.

**Comment by sils** [comment]
Yours it is!
