### ISSUE TITLE
Linter_Bears.rst: Link to API docs

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#21]
_From @SanketDG on August 15, 2016 20:56_

_Copied from original issue: coala-analyzer/coala#2614_

**Comment by Adrianzatreanu** [comment]
_From @swrj on August 17, 2016 17:26_

Could you clarify what is needed to be done?

**Comment by Adrianzatreanu** [comment]
_From @SanketDG on August 17, 2016 18:3_

@swrj sure! 

So in Linter_Bears.rst, there is this piece of text:

> If you need more information about the ``@linter`` decorator, refer to the API
documentation. It's more versatile than described in this little tutorial.

The task is to link the text "API documentation" to our api docs http://coala.readthedocs.io/en/latest/API/modules.html

Let us know if you'd like to work on this.

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on August 17, 2016 18:24_

@SanketDG do we have the possibility to use some "relative" link, so we don't need to link hardcodedly to our website?

**Comment by Adrianzatreanu** [comment]
_From @SanketDG on August 17, 2016 18:48_

Yes we can by using the `:doc:` thing I think
  
```
:doc:`API documentation <API/modules>`
```

**Comment by sils** [comment]
Assigning to @rishus23 as per request on gitter

**Comment by Adrianzatreanu** [comment]
blocking as we dont have any api documentation right now.

**Comment by Adrianzatreanu** [comment]
unblocked as we have api.coala.io, ping @rishus23

**Comment by aptrishu** [comment]
@Adrianzatreanu I'm @rishus23  :P .

**Comment by andreiraduta1101** [comment]
Can I be assigned?

**Comment by aptrishu** [comment]
Assigned.. :+1:

**Comment by andreiraduta1101** [comment]
The tutorial about linter posted doesn't work..

What is to be resolve for this issues clearly?

**Comment by Nosferatul** [comment]
check https://api.coala.io/en/latest/, I believe you should add it on the page
