### ISSUE TITLE
Documentation: Add docs for all the metadata attributes

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#22]
_From @sils1297 on July 24, 2016 12:23_

CC @Udayan12167 @Adrianzatreanu 

_Copied from original issue: coala-analyzer/coala#2553_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on July 24, 2016 12:23_

Thanks for reporting this issue! A coalaian will look at it soon.

**Comment by Adrianzatreanu** [comment]
_From @arush0311 on August 12, 2016 19:2_

Can you tell me what you mean by metadata attributes and where they can be found?

**Comment by Adrianzatreanu** [comment]
I think he's referring to the attributes found in https://github.com/coala-analyzer/coala/blob/master/coalib/bears/Bear.py , such as REQUIREMENTS, CAN_DETECT, LICENSE, etc :D

**Comment by Adrianzatreanu** [comment]
_From @arush0311 on August 13, 2016 16:44_

Can I take this? I might need some help though.

**Comment by Adrianzatreanu** [comment]
feel free to, i can help you if needed

**Comment by Adrianzatreanu** [comment]
This is being moved to https://github.com/coala-analyzer/documentation, please pick it up from there, thank you!

**Comment by arush0311** [comment]
@Adrianzatreanu Is there anything specific that you want me too add? I think the docs are already present in  https://github.com/coala-analyzer/coala/blob/master/coalib/bears/Bear.py from line 46 to 137.

**Comment by Adrianzatreanu** [comment]
@arush0311 as docs we dont mean docstrings, this repository refers to the docs we have on http://coala.readthedocs.io/en/latest/ , and we probably want a separate page for the metadata attributes? im not really sure. @sils1297 ? @Makman2 ?

**Comment by Makman2** [comment]
yeah I think we should have something additional. maybe we could add a paragraph here: https://github.com/coala-analyzer/documentation/blob/master/Developers/Writing_Bears.rst

**Comment by Adrianzatreanu** [comment]
good idea, @Makman2
