### ISSUE TITLE
Add cobot explanation for review

### ISSUE THREAD

**Issue by aptrishu** [coala/documentation#221]
People ask for review in the gitter channel, which is quite difficult to handle for maintainers.
It should explain them how review process works.

**Comment by sils** [comment]
you know that cobot is on gitlab? https://gitlab.com/coala/cobot/

**Comment by aptrishu** [comment]
Yes, I know that so should make a PR there?

**Comment by sils** [comment]
well... yes. Also file the issue there (or don't file an issue, that's fine too)
