### ISSUE TITLE
Use --flush-cache when running helloworldbear

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#225]
In Writing_bears.rst it says you should run ``coala -f src/*.c -d bears -b HelloWorldBear -L DEBUG``, when actually you need to flush your cache because you already ran it with SpaceConsistencyBear before, so change the command to ``coala -f src/*.c -d bears -b HelloWorldBear -L DEBUG --flush-cache``

**Comment by drjod** [comment]
Hi, I luv to work on that
