### ISSUE TITLE
Docs: Rename section "List of module (generated)" -> "API Reference"

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#23]
_From @Makman2 on July 30, 2016 16:52_

If someone needs the API, he/she looks for the word "API". Also "(generated)" does not really help ^^

_Copied from original issue: coala-analyzer/coala#2575_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on July 30, 2016 16:52_

Thanks for reporting this issue! A coalaian will look at it soon.

**Comment by jayvdb** [comment]
This has been achieved via several means.
