### ISSUE TITLE
Mention the change in "Getting started with coala"

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#234]
So after running in the Getting started with coala file the commands:

cd coala-tutorial
coala --files=src/\*.c --bears=SpaceConsistencyBear --save

and the bear shows the problem, it is unclear to some people where the space inconsistency was. i think its helpful to add here an explanation to where exactly the problem was (today some people didnt notice the space after #include <> so they thought coala did nothing).

imo in the guide there should be a git diff shown (as in what the bear changed) and then explaining that there was a trailing whitespace after the include.

**Comment by mei-li** [comment]
Can I get assigned this issue?

**Comment by mei-li** [comment]
@Adrianzatreanu I have a suggestion here, but I didn't use a git diff, because it doesn't display more information than coala printout does already, it is actually the same.

**Comment by sils** [comment]
@mei-li I still didn't see you in the organization, did you accept the invitation?

**Comment by mei-li** [comment]
@sils ups sorry just did now

**Comment by sils** [comment]
@mei-li there you go. Did you ask for assignment on any other issues?

**Comment by mei-li** [comment]
@sils yes but it is already merged

**Comment by mei-li** [comment]
@sils that one https://github.com/coala/coala/issues/2915
