### ISSUE TITLE
Newcomer guide should invite users to solve difficulty/low issues as well

### ISSUE THREAD

**Issue by sils** [coala/documentation#239]
_From @justuswilhelm on October 29, 2016 7:27_

Lasse suggested this and I agree. Devs that are already familiar with how OSS contribution works can already start hacking on difficulty/low issues!

_Copied from original issue: coala/coala#2916_

**Comment by sils** [comment]
_From @justuswilhelm on October 29, 2016 10:20_

Perhaps this issue should be in the documentation repository...

**Comment by yash-nisar** [comment]
@sils There are 2 instances of the following Note: 
> **Do not only fix a newcomer issue!** Supervising newcomers is really a lot of work. We’re all volunteers and we can’t keep this up if you don’t help us in other areas as well!

What about replacing one Note with the following ?
> **Do not only fix a newcomer issue!** It is highly recommmended that you fix one newcommer issue to get familiar with the workflow at coala and then proceed to a **difficulty/low** issue.

**Comment by jayvdb** [comment]
Experienced devs often dont know how to write good patches.

IMO, rather than jumping to low tasks, IMO experienced devs should jump to reviewing some patches first.  Then they are working beside other reviewers, and will pick up some rules they were not aware of.

**Comment by yash-nisar** [comment]
@jayvdb I completely agree with you. How about renaming the issue to 
> Newcomer guide should invite users review difficulty/newcomer issues

and then we can move on to a difficulty/low issue.

**Comment by Adrianzatreanu** [comment]
I've happened to see even experienced devs that struggled with rebases and stuff, so it might not be wise to ask them to start with low.

However, if im not mistaken, we have a PR open that changed the newcomers guide a little and expressed what a newcomer needs to do, quite nicely, and im not sure if it is merged, cuz if it isnt, i think you should wait until it is :)

**Comment by yash-nisar** [comment]
Sure !

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3250
