### ISSUE TITLE
In the README.rst file, the statement above the command prompt should be an example specific to Python

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#24]
_From @RohanVB on July 24, 2016 11:1_

The current command prompt is displayed as : 

> To see what coala can do for your language, run:
> 
> `$ coala --show-bears --filter-by-language Python`

Since we are giving an example, the statement above the command prompt should be specific to Python.

_Copied from original issue: coala-analyzer/coala#2551_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on July 24, 2016 11:1_

Thanks for reporting this issue! A coalaian will look at it soon.

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on July 24, 2016 12:6_

Isn't that obvious? I feel like an example with a real language is more useful than "insert language". Not that I'm sure...

**Comment by Adrianzatreanu** [comment]
_From @RohanVB on July 24, 2016 12:10_

It's obvious, but I don't feel its correct. If python has to be in the prompt, the sentence above should be an example specific to using it with terminal, making it 'For example, to see what coala can do with Python, run:' Because right now one is generalised, the other is specific.

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on July 24, 2016 12:10_

cool so let's change the explanation above?

**Comment by tamj0rd2** [comment]
I'd like to do this

**Comment by tamj0rd2** [comment]
@Adrianzatreanu Where abouts is the line that needs to be edited? I can't find it in README.rst

**Comment by Adrianzatreanu** [comment]
This issue was migrated from coala, it wasnt me who opened it. checking if its still valid

**Comment by Adrianzatreanu** [comment]
it isnt, as its from the coala readme and its not valid anymore.

**Comment by Adrianzatreanu** [comment]
sorry for the inconvenience

**Comment by Adrianzatreanu** [comment]
actually its still valid, but i feel like its so obvious its not needed. if anyone feels like this is needed, reopen.
