### ISSUE TITLE
Review.rst enumerated list syntax problem

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#242]
``` bash
$ rstcheck Developers/Review.rst
Developers/Review.rst:2: (INFO/1) Enumerated list start value not ordinal-1: "6" (ordinal 6)
```

The blocks in `5.` are not indented, so it thinks `6.` is a new list.

**Comment by charlesBak** [comment]
hi @jayvdb can you please explain the issue?

**Comment by jayvdb** [comment]
@charlesBak , please look at the relevant section of the file, and try to fix the syntax.  You may need to read about the syntax of reStructuredSyntax to understand the problem.

**Comment by mihai-burduselu** [comment]
Assign me this!

**Comment by Adrianzatreanu** [comment]
hey @mihai-burduselu you have not accepted our invitation, please check your mail ( i cannot assign you )

**Comment by mihai-burduselu** [comment]
done

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3249
