### ISSUE TITLE
coala_as_Git_Hook: Title underline too short

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#246]
```
$ rstcheck ./Users/coala_as_Git_Hook.rst
./Users/coala_as_Git_Hook.rst:2: (WARNING/2) Title underline too short.
```

**Comment by apoorvkhattar** [comment]
assign this issue

**Comment by Cygnus32** [comment]
Can you please highlight how much should the proper length be, thanks

**Comment by CristianPopa96** [comment]
I would like to work on it.

**Comment by RohanVB** [comment]
@CristianPopa96 still working on this? You can always ask for help on gitter if required :)

**Comment by SanketDG** [comment]
Related issue: https://github.com/myint/rstcheck/issues/23

PR fix: https://github.com/myint/rstcheck/pull/24

Close once merged in.

**Comment by SanketDG** [comment]
Fixed in https://github.com/myint/rstcheck/commit/8387d6e0fb6770a4d9743d5dbcf84bf1b4c3bf83
