### ISSUE TITLE
Development_Setup: Hyperlink target "dev-notes" is not referenced

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#247]
```
$ rstcheck ./Developers/Development_Setup.rst
./Developers/Development_Setup.rst:1: (INFO/1) Hyperlink target "dev-notes" is not referenced.
```

**Comment by arjunsinghy96** [comment]
Hello @jayvdb. Please assign me this issue.

**Comment by arjunsinghy96** [comment]
Dear @sils @jayvdb , I have created a pull request for this issue which also contains a rectification of a minor typo in ./Users/Tutorials. But the pull request is created as #276 . How do I refer to this issue.

**Comment by sils** [comment]
see coala.io/commits , add a closes note
