### ISSUE TITLE
Linter: Documentation for default severity map not complete

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#25]
_From @Makman2 on July 23, 2016 14:49_

Here: https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/abstractions/Linter.py#L686

though this is the map currently supported:
```
severity_map=MappingProxyType({
                    "critical": RESULT_SEVERITY.MAJOR,
                    "c": RESULT_SEVERITY.MAJOR,
                    "fatal": RESULT_SEVERITY.MAJOR,
                    "fail": RESULT_SEVERITY.MAJOR,
                    "f": RESULT_SEVERITY.MAJOR,
                    "error": RESULT_SEVERITY.MAJOR,
                    "err": RESULT_SEVERITY.MAJOR,
                    "e": RESULT_SEVERITY.MAJOR,
                    "warning": RESULT_SEVERITY.NORMAL,
                    "warn": RESULT_SEVERITY.NORMAL,
                    "w": RESULT_SEVERITY.NORMAL,
                    "information": RESULT_SEVERITY.INFO,
                    "info": RESULT_SEVERITY.INFO,
                    "i": RESULT_SEVERITY.INFO,
                    "suggestion": RESULT_SEVERITY.INFO}),
```

_Copied from original issue: coala-analyzer/coala#2537_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on July 23, 2016 14:49_

Thanks for reporting this issue! A coalaian will look at it soon.

**Comment by morganpdx** [comment]
I'd like to work on this issue.  What is the end result?

**Comment by sils1297** [comment]
@Makman2 can you elaborate on what should be happening here? Not clear to me.

**Comment by Makman2** [comment]
Actually this one is an invalid copy from the old issue, which does really belong to the coala-core as it affected API docs :)

@morganpdx but indeed the old `RESULT_SEVERITY.MINOR` wasn't updated correctly when introducing the new `RESULT_SEVERITY.INFO` :)
See https://github.com/coala/coala/issues/2816
