### ISSUE TITLE
Users/Install.rst: `OSX` -> `macOS`

### ISSUE THREAD

**Issue by chauffer** [coala/documentation#256]
difficulty/newcomer

**Comment by chauffer** [comment]
thank gitmate

**Comment by sils** [comment]
huh, this has been fixed by @charlesBak - maybe something wrong with the issue link

**Comment by charlesBak** [comment]
@sils have i done something wrong?

**Comment by sils** [comment]
hEY @charlesBak someone else was just faster and there were two pull requests for this issue. Usually we like people to get an assignment to avoid this but none of you two got one which is why this happened :/

**Comment by charlesBak** [comment]
@sils i have got some help in the chat room on how do the PR since then, i hope ill do a good one soon enough.

**Comment by sils** [comment]
@charlesBak :+1: sorry that we didn't catch this earlier
