### ISSUE TITLE
Add info for installing Java

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#259]
If you install coala and you dont have java, and then you install it, you need to restart your shell for it to work to recogznie you have java installed :) needs to be added in the docs somewhere

**Comment by hit023** [comment]
@aachiritoaei Could you please give a sample of a commit message for an addition to documentation?

**Comment by rrungureanu** [comment]
Assign me this issue, please.

**Comment by WoWClaudiu** [comment]
I would like to work on it

**Comment by OctavianGuzu** [comment]
Assign me this issue !

**Comment by Adrianzatreanu** [comment]
@rrungureanu any news :) ?

**Comment by RaiVaibhav** [comment]
@stephenbhope  are you still working on this

**Comment by jayvdb** [comment]
Unassigned per https://github.com/coala/documentation/pull/420#issuecomment-344136654

**Comment by jayvdb** [comment]
Is this problem still accurately described ?

Wont coala-bears installation fail if java is not installed?  the `language-check` installer checks if java is installed ...??

**Comment by Makman2** [comment]
> If you install coala and you dont have java, and then you install it, you need to restart your shell 

Doesn't this depend also on the OS/package how properly it sets up environment?

**Comment by jayvdb** [comment]
Changing topic from "Add info for installation after you install java" to "Add info for installing Java"

**Comment by jayvdb** [comment]
http://docs.coala.io/en/latest/Users/Install.html doesnt mention Java at all, and it should.

The coala bears that need Java can be found at https://github.com/coala/coala-bears/tree/master/bears/java

The scala bear also needs Java : https://github.com/coala/coala-bears/tree/master/bears/scala

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [4737907299450880](https://codein.withgoogle.com/dashboard/tasks/4737907299450880).
