### ISSUE TITLE
Documentation: Current page's link in sidebar should be highlighted on coala.readthedocs.io

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#262]
_From @beatrix-bodo on October 30, 2016 12:42_

On http://coala.readthedocs.io the current page's link is not highlighted in the sidebar so when someone wants to click on the next page, it's difficult to find what page they are on currently.

_Copied from original issue: coala/coala#2925_

**Comment by Adrianzatreanu** [comment]
_From @sils on October 30, 2016 12:54_

Thanks so much, good point. @Mariatta you had a master issue to track further design suggestions somewhere, right? That sounds like something that shuold be easy to add as well.

**Comment by Mariatta** [comment]
The master issue mentioned by @sils is #203
