### ISSUE TITLE
Add default PR description

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#31]
_From @AbdealiJK on June 23, 2016 4:6_

I was submitting a patch at `scikit-image` and I was really impressed with their default PR message:

```
## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]


## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]


## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]
```

The checklist is really nice and serves as a better reminder of "things to do" as compared to writing it in a documentation.

_Copied from original issue: coala-analyzer/coala#2389_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on June 23, 2016 4:6_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on June 23, 2016 4:7_

You can find their other templates and this one at https://github.com/scikit-image/scikit-image/tree/master/.github

**Comment by Adrianzatreanu** [comment]
_From @hypothesist on July 2, 2016 15:58_

We could also add something about doctests. Also modify the first check point to something like "Run `coala` on the project before submitting" as that should pretty much cover any code standards issue. (We could also convince `scikit-image` devs to use coala.)

**Comment by Gouravchawla** [comment]
Do you have some content in mind for this?

**Comment by sils1297** [comment]
We should probably have a link to coala.io/commit at least, explain people that they should do rebases and stuff like this. Also mention that people should get assigned to an issue when wanting to work on it.

Btw. @Gouravchawla I sent you a community invitation so I can assign you - would you be interested in fixing this? Actually I think this can save us a hell lot of time.

**Comment by Gouravchawla** [comment]
Yes, I would love to work on it. @sils1297

**Comment by adtac** [comment]
@Gouravchawla assigned you :+1:

**Comment by Gouravchawla** [comment]
I apologize for the delay but here is what I came up with based on the scikit's PR template. I welcome suggestions on its improvement.

PR Template:

## Description
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]


## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](http://docs.coala.io/en/latest/Developers/Codestyle.html)
- [ ] Commit messages that follow the instructions given [here](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html)
- [ ] [Tests](http://docs.coala.io/en/latest/Developers/Writing_Tests.html)

[For detailed information on these and other aspects see [contribution guidelines](https://github.com/coala/coala/blob/master/CONTRIBUTING.rst)]


## References
[If this is a bug-fix or enhancement, it closes issue # ]

**Comment by underyx** [comment]
As far as I know, you can use comments in markdown, actually, so instead of


```
[Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images.]
```

we could have

```
<!-- Tell us about your new feature, improvement, or fix! If relevant, please supplement the PR with images. -->
```

which doesn't need to be deleted by the reporter.

**Comment by Gouravchawla** [comment]
Ok, i'll turn that into comments. The checklist would still need to be removed though, isn't it?

**Comment by Adrianzatreanu** [comment]
is this still needed?

**Comment by sils** [comment]
yes we should ideally replace the gitmate autoresponse with good PR
templates everywhere

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by jayvdb** [comment]
Moved to https://github.com/coala/meta/issues/117
