### ISSUE TITLE
Mention somewhere that `--show-bear-languages` can accept multiple languages

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#34]
_From @hypothesist on June 11, 2016 11:29_

After @sils1297 's PR is merged, it's `--filter-by-language`.

We can give space separated langauge names. We should also possibly introduce comma-separated.

_Copied from original issue: coala-analyzer/coala#2311_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on June 11, 2016 11:29_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by lqaz** [comment]
I'm on this.

**Comment by Adrianzatreanu** [comment]
Hey, ive sent you an invitation to our org, accept it by mail or on github.com/coala. join us on gitter! :D https://gitter.im/coala/coala

**Comment by sils1297** [comment]
@lqaz it's yours! Thanks for the help.

**Comment by shrutishrm512** [comment]
This information can be added in Users/Tutorial.rst file like by giving example:
`coala --show-bears --filter-by-language C python`
or by giving separate heading and explaining in it like `Show bears Information` part in the Tutorial.rst file.
Is this way correct ?

**Comment by adtac** [comment]
I like the idea of modifying the default example in Users/Tutorial.rst to have C and Python. This way we don't use too much extra space (and add redundant examples), but still convey the message across.

**Comment by shrutishrm512** [comment]
yes, sure ! @adtac I can add one more example for multi languages mentioning in command.

**Comment by adtac** [comment]
No, *modify* the existing one. That should be a good example of both - how you can get the bear list with `--show-bears` and that you can give multiple languages. There's no need for another example.

**Comment by shrutishrm512** [comment]
okay! thanks @adtac :+1:
