### ISSUE TITLE
Advise newcomers to use branches instead of master in the "newcomer's guide"  page

### ISSUE THREAD

**Issue by Mixih** [coala/documentation#341]
Recently, I have seen quite a few people who patch coala from their master branch. This is a recipe for losing changes and screwing up rebases(basically disaster). We should probably advise them not to in the newcomers guide.

**Comment by jayvdb** [comment]
We were working on an "PR auto-close" if the PR had branch name "master".
https://gitlab.com/gitmate/IGitt/merge_requests/36 was done to support this.
@sils, what is the next step?

I have manually done the PR close here : https://github.com/coala/coala-html/pull/101#issuecomment-264702835

**Comment by jayvdb** [comment]
OK, I found it : https://gitlab.com/gitmate/gitmate/issues/86

**Comment by Mixih** [comment]
This issue was moved to coala/coala#3148
