### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by Mixih** [coala/documentation#345]
>Can I Use coala in my Continuous Integration?
>
>Yes! There’s a dedicated coala-ci binary that is noninteractive, shows results cleanly in the log and returns error codes if something is wrong.

There is no coala-ci binary anymore, it's a command line flag now

in section `What are those things failing/passing on my Pull Request?`
>scrutinizer Checks for the code quality, and points out all the code elements that were added, such as functions, classes, etc.

I don't think we use scrutinizer anymore

**Comment by dracarys09** [comment]
@Mixih in the second question 'scrutinizer' part should be removed ?
I think the answer to the first question is already corrected...

**Comment by Mixih** [comment]
yep the first one has been fixed, so only one left is to kill off any scrutinizer references if they are present, if they are all gone, then ping me to close this

**Comment by Mixih** [comment]
unassigned per request

**Comment by jayvdb** [comment]
Scrutinizer is https://github.com/coala/documentation/issues/376

**Comment by dracarys09** [comment]
there is already an isses for Scrutinizer as @jayvdb  mentioned... There is no need for this one... We should just close it...

CC @Mixih

**Comment by Mixih** [comment]
agreed, closed
