### ISSUE TITLE
Show for `--apply-patches` what command is actually shortcutted

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#35]
_From @Makman2 on June 6, 2016 2:16_

--> `-S default_actions="*: ApplyPatchAction"`

_Copied from original issue: coala-analyzer/coala#2303_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on June 6, 2016 2:16_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on June 6, 2016 2:17_

Do we want this to appear inside the argparse help for `--apply-patches`?

**Comment by jayvdb** [comment]
We should also ensure that `default_actions="*: ApplyPatchAction"` is properly documented.

**Comment by jayvdb** [comment]
Assigning to a developer to get this closed before GCI.
