### ISSUE TITLE
Document bear API

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#36]
_From @sils1297 on June 4, 2016 16:20_

_Copied from original issue: coala-analyzer/coala#2276_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on June 4, 2016 16:20_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @abhsag24 on June 5, 2016 7:37_

@sils1297 you mean the bear class?

**Comment by Adrianzatreanu** [comment]
it's unclear to me either, what exactly do you want to be documented?

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on June 17, 2016 8:42_

The API a bear writer can use to create a bear

**Comment by Adrianzatreanu** [comment]
So you basically want a website on readthedocs where one could specify all the methods for the class which he has available and how he should write that bear?

**Comment by Adrianzatreanu** [comment]
_From @abhsag24 on June 17, 2016 14:0_

so we should have tutorials for `Diff` and `SourceRange` too right?

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on June 17, 2016 14:2_

Currently if you want to write a bear, you have to go through the tutorial
which is not always what you want, sometimes you want a quick API reference
and work out your own stuff

**Comment by meetmangukiya** [comment]
I guess this has been done now :thinking: with api.coala.io ?

**Comment by sils** [comment]
we have to check if the current doc is sufficient and link to it

**Comment by Mixih** [comment]
This issue was moved to coala/coala#3146
