### ISSUE TITLE
Add CircleCI to Users/Docker_Image

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#379]
Users/Docker_Image currently provides configuration for GitLab CI and Travis CI.

Circle CI should also be added.
See https://circleci.com/docs/docker/

**Comment by vijeth-aradhya** [comment]
@jayvdb I would like to take up this issue.
Just to clear things out, I just have to add docker for `services` and the script for `tests` right? ( in the `Running tests in a container` section in the above link )
