### ISSUE TITLE
Bash autocompletion for coala does not add anything?

### ISSUE THREAD

**Issue by Naereen** [coala/documentation#388]
Hi,

I followed the instructions [about autocompletion](https://docs.coala.io/en/latest/Users/Shell_Autocompletion.html), with latest versions of `coala` and `argcomplete`, and [updated](https://bitbucket.org/lbesson/bin/commits/886cfca#L.bashrcT422) my `.bashrc` as suggested, but absolutely nothing has changed: the autocompletion for `coala` command line program is not loaded (on the same shell or a new shell).

Any one else having the same issue ?
(I'm on XUbuntu 16.10, Bash v4.3, coala 0.9.1, argcomplete 1.7.0 on Python 3.5.2)

Any idea of what can I do to fix it ?
Thanks in advance.

**Comment by Naereen** [comment]
Note: this issue could possibly be for [coala/coala](https://github.com/coala/coala) repository instead.

**Comment by sils** [comment]
Hm I have spoken with someone somewhen with the same issue but I wasn't able to reproduce it yet...

**Comment by Naereen** [comment]
I think a possible explanation is that the script `/usr/local/bin/coala` (result of `$(which coala)`) is only 5-line long, and does not contain for itself the calls to the `argparse` module. So maybe that's why the `argcomplete` script fails to generate completion for it?

If you think that could be it, I will find the "complete" `coala` script and call `register-python-argcomplete` on it, to see if it changes anything.

**Comment by sils** [comment]
Don't think so, as it works for others...

The coala script is generated, it imports a main method and runs it. This is needed because those scripts are a bit platform dependent, Windows greets.

**Comment by sils** [comment]
@Naereen indeed it doesn't work with bash for me as well :/ with ZSH it works fine, that's what I use normally. I'm currenlty checking https://pypi.python.org/pypi/argcomplete for what we're doing wrong.

**Comment by Naereen** [comment]
OK. Thanks for trying. Please tell me if I can be of any help.

**Comment by all3fox** [comment]
For me autocompletion does *not* work for *both* global install and virtual environment install with bash `4.4.12`, argcomplete `1.8.2` and coala `0.10.0`.

When I switch to zsh, autocompletion works for global install but does *not* work, when I install everything in a virtual environment. My zsh is `5.3.1`

Personally, I find it strange that for me there is no autocompletion in virtual environments.

**Comment by all3fox** [comment]
Ok. Here is what works for me now:

Bash `4.4.12`
----------------

Turns out, https://github.com/kislyuk/argcomplete packs a script called `register-python-autcomplete`. I ran:

```
register-python-autocomplete --shell bash coala
```

and pasted the output of this script into my `.bashrc` instead of the line

`eval "$(register-python-argcomplete my-awesome-script.py)"`

recommeneded by docs of both projects (coala and argcomplete)

After that, autocompletion worked for me both globally and in a virtualenv.

Zsh `5.3.1`
-------------

As I said before, autocomplete outside of the virtualenv works as by documentation. When I switch inside the virtualenv, it breaks. However, `source ~/.zshrc` brings it back to life.

@sils and @Naereen, could you confirm that it fixes your issues?

**Comment by Naereen** [comment]
Now it works, by using your trick. :clap:

Instead of changing a `.bashrc` file, [I added](https://bitbucket.org/lbesson/bin/commits/f414249) the response of `register-python-argcomplete --shell bash coala` as a `coala.bash_completion` file, in my `~/.bash_completion.d/` folder.

Thanks @all3fox for following up on this issue. (it's OK to close it now?)

**Comment by all3fox** [comment]
cobot assign me

cobot mark newcomer

**Comment by Naereen** [comment]
OK.
I don't know what script is that, the only one I have is `register-python-argcomplete`, not `register-python-autocomplete` (and even the latest version has no `auto..`)

**Comment by all3fox** [comment]
sry, sry, I am on the go right now, did not check the script name. Nevermind, we will take care of the issue from here, thanks )
