### ISSUE TITLE
Modify PylintTutorialBear description

### ISSUE THREAD

**Issue by dracarys09** [coala/documentation#396]
https://coala.readthedocs.io/en/stable/Users/Tutorials/Linter_Bears.html#finished-bear
https://api.coala.io/en/latest/Developers/Writing_Linter_Bears.html

"Check for codings standards" should be "Checks for coding standards"

**Comment by SiddharthKumar02** [comment]
I would like to get assigned to this

**Comment by jayvdb** [comment]
https://coala.readthedocs.io/en/stable/Users/Tutorials/Linter_Bears.html#finished-bear -- this file doesnt exist any more.  It was moved to the documentation repository https://github.com/coala/coala/commits/master/docs/Users/Tutorials/Linter_Bears.rst , and then ... disappeared. ;-)

**Comment by jayvdb** [comment]
It appears three times in the file.
```
git grep 'codings standards'
docs/Developers/Writing_Linter_Bears.rst:        Check for codings standards (like well-formed variable names), detects
docs/Developers/Writing_Linter_Bears.rst:        Check for codings standards (like well-formed variable names), detects
docs/Developers/Writing_Linter_Bears.rst:      Check for codings standards (like well-formed variable names), detects
```
