### ISSUE TITLE
using imperative tense in commit messages

### ISSUE THREAD

**Issue by arush0311** [coala/documentation#398]
I think a lot of people make mistake of not using imperative tense in commits messages..
I think we should add the following in writing good commit messages

```
When you add a commit message think of what the commit will do if it gets merged (not what you have done)
eg: 
applied a strip method to language string
to
Strips the whitespaces in language string
```
It helped me a lot. :D

**Comment by supergr35** [comment]
Wrong repo, this is for coala user documentation.

By the way, the second one isn't actually in the imperative mood, if it was it would be `Strip the whitespaces in language string`
