### ISSUE TITLE
Self_Correcting_Bears.rst needs an update

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#41]
_From @Makman2 on May 17, 2016 19:22_

Linter v2 API is there, should be used instead :+1:

_Copied from original issue: coala-analyzer/coala#2160_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on May 17, 2016 19:22_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Makman2** [comment]
commits there in https://github.com/coala-analyzer/coala/pull/2588

**Comment by Adrianzatreanu** [comment]
ah i have already done this. we have moved the docs in another repo.. could you move your commits here accordingly? we will remove docs from coala soon..

**Comment by Makman2** [comment]
sure :+1:

**Comment by Makman2** [comment]
`Self_Correcting_Bears.rst` gets delete in https://github.com/coala-analyzer/documentation/pull/68 .

**Comment by Makman2** [comment]
File is deleted, docs for Linter v2 API do exist.
