### ISSUE TITLE
Document Config Generation

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#42]
_From @sils1297 on May 14, 2016 18:51_

_Copied from original issue: coala-analyzer/coala#2145_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on May 14, 2016 18:51_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on May 14, 2016 18:51_

for linter

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on May 30, 2016 16:44_

I think the best way is to make a website which has a table of the configs being used right now, the documentation related to that param, and the bears it's being used in. This website/webpage should have a search box for easy searching and should be auto generated from the bears itself.
This webpage would help third party bear writers too ! And would be a really cool one-page documentation of all the "features" coala provides. And also which bears it provides them in.

Possible methods of doing this:
 - Make a parser using our documentation parsing routines and create a webpage with it. And then link this in the docs.
 - Configure sphinx to autogenerate this (somehow? if it's possible...) I think sphinx is pretty flexible ?

I think this page should reside in our documentation and should be "autogenerated" in every readthedocs build.

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on May 30, 2016 16:54_

@AbdealiJK are you sure this comment was on the right issue? Did you mean to comment on https://github.com/coala-analyzer/coala-bears/issues/460 ?

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on May 30, 2016 18:3_

Yes indeed. I confused the issues.
It was meant for https://github.com/coala-analyzer/coala-bears/issues/460

**Comment by jayvdb** [comment]
Hmm.

There should be a documentation page about `coala-quickstart`.
Assigning to get that started properly, and this extremely old issue closed.

**Comment by satwikkansal** [comment]
So a page explaining what coala-quickstart does at http://docs.coala.io (i.e. [here](https://github.com/coala/documentation/tree/master/Users)? I think that's a good idea, most people don't use quickstart because they aren't aware of it.

**Comment by jayvdb** [comment]
A very basic page.  Just get the ball rolling.  Negotiate who does it.  We'll get it merged quick, and then create new issues for extra things that should be added.

**Comment by palash25** [comment]
A basic layout for the `quickstart.rst` could be
- Installation
- Features
- Usage

We can distribute these sections amongst ourselves @ishanSrt 
Let me know if I have missed something.
