### ISSUE TITLE
New section inheritance documentation.

### ISSUE THREAD

**Issue by Udayan12167** [coala/documentation#428]
`default` section is deprecated and section inheritance is implemented.

**Comment by jayvdb** [comment]
I think this was mostly done in https://github.com/coala/documentation/pull/437 .

**Comment by mridubhatnagar** [comment]
@Udayan12167 @Mixih can you please have a look at the PR.

**Comment by meetmangukiya** [comment]
I think @Mixih has already done this during the release

**Comment by mridubhatnagar** [comment]
@meetmangukiya this was an open issue so I took it up. And raised a PR. Should we close this?
