### ISSUE TITLE
Add crosstesting in the docs

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#43]
_From @AbdealiJK on April 26, 2016 1:52_

It would be nice to give a method of things to add if we want to crosstest things between coala and coala-bears as @Makman2 had to do for the Linter stuff.
Would be good to add to docs (so that if the branch which did this last time was deleted, it doesnt matter)

The last PR with crosstest is here: https://github.com/coala-analyzer/coala-bears/pull/314

Assigning Makman as he's the best one to do this I think

_Copied from original issue: coala-analyzer/coala#2074_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on April 26, 2016 1:52_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on April 26, 2016 11:0_

I think that doesn't belong to the docs :O Let's just keep my branch and everything is fine, we adjust it as needed^^ As we hack quite into the CI we shouldn't make this "official"^^

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on April 26, 2016 11:59_

Then I think we should clean it up and make an easy method of doing this

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on April 26, 2016 13:45_

Is there an easy way? :O

**Comment by Makman2** [comment]
Honestly I don't want to add that, this is CI hacking. I have a branch which works with such things, if someone needs crosstesting, someone should ping me or ask around the gitter channel until the messages reach me :)

**Comment by Makman2** [comment]
@AbdealiJK ping me if you still think we should add that to the docs. But then you'll get assigned :P :P
