### ISSUE TITLE
Enable RST linting bears on this repo

### ISSUE THREAD

**Issue by Mixih** [coala/documentation#432]
Currently, this repository is not being linted for rst problems. Please enable both reSTLintBear and RSTCheckBear. There are probably issues with the rst which need fixing first. Please spawn newcomer sub-issues for each one found, or fix them yourself.

**Comment by mridubhatnagar** [comment]
Hey, I went through 
1)http://docs.coala.io/en/latest/Users/Tutorial.html .
2) Went through .coafile

Can you guide me how to proceed further. So that I can make some progress and help in resolving this issue.

**Comment by Mixih** [comment]
see the rst section int he main coala repo for some inspiration. You probably want both reSTLintBEar and RSTCheckBEar.

**Comment by mridubhatnagar** [comment]
Went through .coafile in the main coala repo. Seems reSTLintBear is already present in .coafile.
do I just need to add RSTCheckBear. 
And files=docs/**/.rst .

**Comment by mridubhatnagar** [comment]
Please can someone look into this commit. And tell me regarding the needful changes before I raise a final PR. Changes other than the newline that needs to be added.

**Comment by jayvdb** [comment]
@Mixih , @mridubhatnagar , @SanketDG , in light of https://github.com/coala/coala-bears/issues/1716 , why do we want to enable both reSTLintBear and RSTCheckBear.  What advantages are their for using reSTLintBear ?  Does it show errors that RSTCheckBear doesnt show?

RSTCheckBear already solves these problems ( https://github.com/myint/rstcheck/issues/1 ) with [config](https://github.com/myint/rstcheck#configuration) like:
```
[rstcheck]
ignore_directives=one,two,three
ignore_roles=src,RFC
```

**Comment by SanketDG** [comment]
@jayvdb I just ran stuff on two bears, and it looks like `rstcheck` has sphinx support by default, so it reports none of those, there is not even config file needed!

@mridubhatnagar please remove reSTLintBear and only use RSTCheckBear :+1:

**Comment by mridubhatnagar** [comment]
Sure, Thanks . Shall do it by today.

**Comment by mridubhatnagar** [comment]
If I keep just the RSTCheckBear. Title underline too short error stems up. Even after changing the length of underline. I am using python 3.4.2.
