### ISSUE TITLE
Update coala banner on README

### ISSUE THREAD

**Issue by yukiisbored** [coala/documentation#436]
The banner on [coala/coala](https://github.com/coala/coala) has changed into a more modern look to match the new website. I think the same thing should be done as well on this repository for uniformity.

**Comment by yashasingh** [comment]
@yukiisbored I would like to work on this issue.

**Comment by yukiisbored** [comment]
@yashasingh Hey, head over to our gitter chat and ask @co-robo to assign yourself to this issue by doing `corobo assign <issue link>`. Have fun!
