### ISSUE TITLE
FAQ: "Can I Use coala in my Continuous Integration?" - Include exit-codes link

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#442]
Currently it states:
> Yes! There’s an argument –ci that runs the coala binary in non-interactive mode, which shows results cleanly in the log and returns error codes if something goes wrong.

We should link to the exit code page so someone can immediately find it. Especially googling "coala exit codes" has given me the FAQ as a first hit.

The exit codes can be found in `Users/Exit_Codes.rst` in this repo and the webpage is currently residing here on our website: https://docs.coala.io/en/latest/Users/Exit_Codes.html

**Comment by AnishHota** [comment]
I will like to work on the issue. This will be my first PR,if i could do it correctly.
