### ISSUE TITLE
Writing a coala Configuration File (coafile and coarc) doesnt show what can actually be used within the coafile

### ISSUE THREAD

**Issue by latacz-io** [coala/documentation#446]
[Writing a coala Configuration File (coafile and coarc)](http://docs.coala.io/en/latest/Users/coafile.html#) describes only the structure of the coafile. Which is confusing, because the title suggest, that the page will teach you how to write the coafile.

So when the user finished read the above page, the user knows how to structure the file, but doesnt know which setting he can actually use, etc.

A link to http://docs.coala.io/en/latest/Users/Tutorial.html in the beginning and the end could be a quick fix

**Comment by Makman2** [comment]
Good point actually :+1:

**Comment by mridubhatnagar** [comment]
In the starting of http://docs.coala.io/en/latest/Users/coafile.html# there is already a link referencing to  http://docs.coala.io/en/latest/Users/Tutorial.html.

**Comment by seven-binoche** [comment]
@mridubhatnagar you're right. Which is why I added the link only at the end.
