### ISSUE TITLE
docs: Add information about the use of labels

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#46]
_From @Uran198 on April 13, 2016 16:16_

From the discussion in https://github.com/coala-analyzer/coala/issues/1875.
There should be an information in the contribution guide on what some labels imply, i. e.:
- if there is difficulty to the issue, then it is ready to be worked on.
- if there are no labels - it's pending review
- if there is a label `status/needs design` or `status/needs info` - there is still an ongoing discussion either on how to implement it, or should it be implemented.

_Copied from original issue: coala-analyzer/coala#2009_

**Comment by Adrianzatreanu** [comment]
_From @gitmate-bot on April 13, 2016 16:16_

Thanks for reporting this issue!

Your aid is required, fellow coalaian. Help us triage and solving this issue!

CC @sils1297, @AbdealiJK

**Comment by rowmatrix** [comment]
I would like to work on this, you can assign me. Where should this doc be placed?

**Comment by sils1297** [comment]
@Uran198 can you hlep ^

**Comment by Uran198** [comment]
Hey, @rowmatrix , I am not quite sure what the best place would be. Somewhere in [newcomers guide](http://docs.coala.io/en/latest/Developers/Newcomers_Guide.html) would probably be OK, or maybe creating new in the `For Developers` section of the docs, maybe in FAQ. Use your best judgment for that.

The guidelines are basically the same as in issue description. It doesn't matter a lot how would you formulate it, as long as it has the same meaning. The only thing, I wanted to do with this is to clarify things a little bit.

**Comment by rowmatrix** [comment]
@sils @Adrianzatreanu  I don't think this is a good fit for me, someone else should take over.

**Comment by sils** [comment]
@rowmatrix thanks, maybe I'll fix this up keeping you as author of the commit because your stuff seems to be rather close to whats needed.

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3265
