### ISSUE TITLE
Document that the docker does not support Python 2 analysis

### ISSUE THREAD

**Issue by co-robo** [coala/documentation#477]
See also coala/docker-coala-base#244
difficulty/low
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=59f723670cef4fed2ebc8aad)

**Comment by ayush1999** [comment]
@jayvdb  @Makman2 I'd like to work on this. Can you please tell me which documentation file is this issue talking about? :)

**Comment by Passionatecricketer** [comment]
This is issue is still opened?

**Comment by ayush1999** [comment]
@Passionatecricketer I've already opened a PR which might be merged soon, as all work is already done. Please find some other issue to work on :)
