### ISSUE TITLE
Document default_coafile

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#480]
From https://github.com/coala/coala/issues/3388:

> default_coafile can be used to solve problems like #3131 . How and when it is used & modified should be in the dev docs.

**Comment by Makman2** [comment]
The docs already mention the `default_coafile`, however right now only its existence is mentioned.

**Comment by newbazz** [comment]
Ok so I sud make a new PR on this repo right

**Comment by newbazz** [comment]
which file btw :P

**Comment by Makman2** [comment]
Yes :+1:
