### ISSUE TITLE
Improve newcomers guide to recommend verifying the bug exists before being assigned

### ISSUE THREAD

**Issue by co-robo** [coala/documentation#487]
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=59fd46630cef4fed2ebcc62a)

**Comment by jayvdb** [comment]
note the newcomers guide is in the coala/coala repository.

**Comment by jayvdb** [comment]
@AGZain , I am unassigning you so our Google Code-in participants can do this.

**Comment by jayvdb** [comment]
(Invalid as the issue is in the wrong repository)

**Comment by jayvdb** [comment]
Moved to https://github.com/coala/coala/issues/5802
