### ISSUE TITLE
FAQ.rst: "ask us!" link not working

### ISSUE THREAD

**Issue by prashant0598** [coala/documentation#492]
The ask us link in FAQ.rst is not working and showing a 404 error.
label:initiatives/gci

**Comment by Makman2** [comment]
Seems it's relatively linking...

**Comment by jayvdb** [comment]
http://docs.coala.io/en/latest/Help/FAQ.html

**Comment by athulpn** [comment]
I am new to open-source. Can i work with that? @prashant0598

**Comment by Makman2** [comment]
@athulpn please follow our [newcomer guide](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html) before starting to work on an issue ;) (especially get assigned)

**Comment by realslimshanky** [comment]
I would like to help out fixing this issue. Sending a PR soon.

**Comment by prnvdixit** [comment]
@realslimshanky This is a GCI issue - Are you in GCI? If so, then first claim the issue in GCI dashboard before starting to work on the issue :smile:

**Comment by realslimshanky** [comment]
@prnvdixit sorry I'm not a GCI member. I'll look into other issues. Thanks
