### ISSUE TITLE
coafile.rst: Fix bad setting example codeblock markup

### ISSUE THREAD

**Issue by co-robo** [coala/documentation#499]
difficulty/newcomer
Opened by @mamat-rahmat at [Gitter](https://gitter.im/coala/coala?at=5a17699571ad3f87362236cb)

**Comment by 0x48piraj** [comment]
**I want to do it!**

BTW, @co-robo Are you talking about : 

> #bad! setting1 = 1
[section1] # setting1 is inherited setting2 = 2

**Comment by mamat-rahmat** [comment]
Yes, exactly

**Comment by 0x48piraj** [comment]
Got it :sunglasses:

**Comment by Kunalgarg2100** [comment]
Can I take it up?

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by mrsaicharan1** [comment]
@co-robo  Can I take this issue up?

**Comment by pavankrishna13** [comment]
I want to work on this issue. Can I get assigned?

**Comment by Makman2** [comment]
You both already have newcomer issues assigned, so please continue with a `difficulty/low` one ;)

**Comment by Naveenaidu** [comment]
I want to work on this issue. Can i get assigned to it?

**Comment by Naveenaidu** [comment]
#532 Can you please review the PR. Please let me know, if i have to make changes to it.
