### ISSUE TITLE
Add descriptions to coalang keys

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#50]
_From @hypothesist on March 6, 2016 12:44_

https://github.com/coala-analyzer/coala/blob/master/coalib/bearlib/languages/definitions/__init__.py is currently undocumented.

_Copied from original issue: coala-analyzer/coala#1824_

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on March 6, 2016 16:11_

What keys are missing?

**Comment by Adrianzatreanu** [comment]
_From @hypothesist on March 6, 2016 16:11_

The _descriptions_ of the keys is missing, not the key itself.

**Comment by Adrianzatreanu** [comment]
_From @hypothesist on March 6, 2016 16:12_

Something like what `names` is, `extensions` is, ... (it's a new-comer issue I think)

**Comment by Adrianzatreanu** [comment]
_From @Makman2 on March 6, 2016 16:13_

Ah sorry, yeah that's good :+1:

**Comment by mohbharti** [comment]
assign me this issue

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by sils** [comment]
Ok this issue is badly described and outdated. I'm truly sorry :/

**Comment by adtac** [comment]
Meh, I don't even remember anything about this :D

Plus coalang has changed a lot since, so I'm not sure if this issue is even relevant still.

**Comment by sils** [comment]
yeah @userzimmermann wanted to add some "model" to the new Languages so they can be type checked and we can (and should) add descriptions

**Comment by userzimmermann** [comment]
And **userzimmermann** will do that modeling soon!
