### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md: Change cobot to corobo

### ISSUE THREAD

**Issue by co-robo** [coala/documentation#503]
label: difficulty/newcomer initiatives/gci
Opened by @Vamshi99 at [Gitter](https://gitter.im/coala/corobo?at=5a1e52adffa3e37919d24f07)

**Comment by apsknight** [comment]
Please assign this issue to me.

**Comment by Vamshi99** [comment]
Ask in gitter or zulip chat

**Comment by Makman2** [comment]
@apsknight please don't start working on issues without assignment, we won't review relevant PRs.
Anyway, invitation is out, and please read our newcomer guide ;)

**Comment by duskybomb** [comment]
@Makman2 assign this to me!

**Comment by Makman2** [comment]
@duskybomb You already have a newcomer issue assigned :+1:
