### ISSUE TITLE
Sudo required while running coala/base using docker

### ISSUE THREAD

**Issue by newbazz** [coala/documentation#513]
difficulty/newcomer

**Comment by Makman2** [comment]
@newbazz what do you want to change specifically actually?

**Comment by Prabhat-IIT** [comment]
I think newbazz wanted to change some command in documentation which requires `sudo` to be written but he has not mentioned where he want changes to be done!

**Comment by Makman2** [comment]
we should be always careful with `sudo` because it depends on the environment. Some don't even have `sudo` available, or they already have root rights. This really depends on the system^^

**Comment by Prabhat-IIT** [comment]
Yup! you're right. Let newbazz clear what he wants then!

**Comment by Makman2** [comment]
And I think it's usually safe-explanatory to use root-rights if something is globally installed. And actually the usual docker installation involves to add a package repository, which forwards this problem to the package manager used.

**Comment by newbazz** [comment]
@Makman2 while i was making a fresh install using docker image, it always gave some permission denied error and I then had to run it using `sudo` so i filed this issue ;P

**Comment by Makman2** [comment]
Don't we defer the docker installation instructions to the official docker documentation?

**Comment by Makman2** [comment]
And are you talking actually about running the `coala/base` image or installing docker itself?

**Comment by newbazz** [comment]
running the coala/base image.

**Comment by Makman2** [comment]
That shouldn't be written in the docs with sudo. Usually users add their username to the docker group so they can access docker functionality without being root, this is very common.

I would vote for closing this issue as invalid, this highly depends on the user setup, and people should read the official docker docs.

@newbazz what do you think? ;)

**Comment by newbazz** [comment]
@Makman2 yeah i agree in your view. I am than closing it.

**Comment by newbazz** [comment]
Closing due to invalid issue.
