### ISSUE TITLE
Unable to generate HTML document file   

### ISSUE THREAD

**Issue by Aakarshak1** [coala/documentation#514]
I tried to generate html file using given instruction here :
https://github.com/coala/documentation 
and got error  

``Exception occurred:
  File "conf.py", line 20, in <module>
  from coalib.misc.Constants import VERSION
ImportError: No module named coalib.misc.Constants
The full traceback has been saved in /tmp/sphinx-err-_10BnE.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 1
`` 
OS - linux ubuntu 16.04
any suggestion?

**Comment by Prabhat-IIT** [comment]
I think extensions (or modules to document with autodoc) are in another directory.You can add those directories to `sys.path` in `conf.py`
