### ISSUE TITLE
Install.rst: Add note for virtualenv creation

### ISSUE THREAD

**Issue by anctartica** [coala/documentation#515]
`virtualenv venv` command in [Installing coala Natively](http://docs.coala.io/en/latest/Users/Install.html) should be changed to `virtualenv venv -p $(which python3)`  along with the note
> NOTE: If you have both Python 3 and Python 2 installed try this command it creates an isolated Python 3 environment called coala-venv in your current directory, as coala only works for Python >= 3.4

Refer to [development setup notes](https://api.coala.io/en/latest/Developers/Development_Setup.html) under using virtualenv section.

**Comment by Makman2** [comment]
How can you use `virtualenv` if you don't have it installed before?

**Comment by anctartica** [comment]
Accidentally had the wrong command. Edited the `pip3 install virtualenv` to `virtualenv venv` in the issue description.

**Comment by Makman2** [comment]
There's also a note I just see:
> NOTE: If you have both Python 3 and Python 2 installed try this command it creates an isolated Python 3 environment called coala-venv in your current directory, as coala only works for Python >= 3.4

Could you maybe point to the exact location where you want to change the command?

**Comment by anctartica** [comment]
done!

**Comment by diveshuttam** [comment]
Hey I would like to work on this issue.

**Comment by diveshuttam** [comment]
HI @Makman2 ,
I have accepted the invitation. pls assign me to the issue. :smile:
