### ISSUE TITLE
Correct the installation instructions for the coala docs

### ISSUE THREAD

**Issue by Uditgulati** [coala/documentation#523]
To generate the documentation of coala it is given in the [Installation guide](http://docs.coala.io/en/latest/Users/Install.html#generating-documentation) notes to use ``make`` instead of ``python setup.py docs``. Later one is now the right way to build the documentation. Hence, it needs to be updated.

**Comment by Makman2** [comment]
@Uditgulati are you sure? I think in this case using `make` is correct, I see a `Makefile` in this repo^^

**Comment by Uditgulati** [comment]
@Makman2   https://github.com/coala/coala/issues/5062 in this issue, it is given that it needs to be updated in this repo too.

**Comment by Makman2** [comment]
I guess this was a bit confusing:

> The user-guide needs modifications in the documentation repo, but the mentioned developer-guide is here. Please use git grep to find the file.

Documentation generation is not part of a user-guide, it's technical documentation.

**Comment by Makman2** [comment]
And here it refers to the generation of the user-documentation itself (which lies also here).

**Comment by Uditgulati** [comment]
Yup, ``make`` is to be used here. Is there any modification required in this repo regarding this issue https://github.com/coala/coala/issues/5062?

**Comment by Makman2** [comment]
I guess no :)
