### ISSUE TITLE
Update `Review` Docs

### ISSUE THREAD

**Issue by nemaniarjun** [coala/documentation#529]
http://api.coala.io/en/latest/Developers/Review.html

A lot of policy has been changed, that has not been reflected in the docs.
The ones I know of currently are:
[ ] Ack is now supposed to be done by maintainers only, other should use "Looks good" or "LGTM" (Lets get this merged)
[ ] We are not using rultor anymore.

**Comment by himanshu1603** [comment]
@nemaniarjun can I take up this issue?

**Comment by nemaniarjun** [comment]
Sure a maintainer will be here to assign you soon, or ask on gitter :)

**Comment by Makman2** [comment]
Please accept the org invite @himanshu1603 , then you can be assigned.

**Comment by monsij** [comment]
Can I be assigned this issue @Makman2 due to user inactivity?
