### ISSUE TITLE
Docs: Reference Lint api module in docs

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala/documentation#55]
_From @AbdealiJK on February 24, 2016 2:39_

I notice that there are a few small things not there in `Linter_Bears.rst` like `use_stderr` ( @SanketDG didnt know about it :( )

Can we link the module documentation directly in RST files ? So they'd see the docstrings ?

Or do we again rewrite these types of documentations in Linter_bears.rst ? (I prefer just linking the API - it's really well documented ! ... although I wrote it, so i could be biased)

_Copied from original issue: coala-analyzer/coala#1686_

**Comment by Adrianzatreanu** [comment]
_From @sils1297 on February 24, 2016 9:30_

sure, why not

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-24 3:39 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Adrianzatreanu** [comment]
_From @AbdealiJK on February 25, 2016 4:15_

So, what needs to be done is add a link to the Lint.py file in Linter_Bear.rst and Self_Correcting_Bear.rst

**Comment by Makman2** [comment]
Update:
The links need to be made to the new `@linter` decorator, though API for it is not working and not rendering currently, so it's blocked by https://github.com/coala-analyzer/documentation/issues/26 .

**Comment by sarthak268** [comment]
please assign me this

**Comment by Makman2** [comment]
`Lint.py` and `Self_Correcting_Bear.rst` do not exist any more, this issue is not appropriate.
Sorry @sarthak268 , ya need to choose a different issue :/
