### ISSUE TITLE
Getting in Touch: Add CoC

### ISSUE THREAD

**Issue by jayvdb** [coala/documentation#553]
http://docs.coala.io/en/latest/Help/Getting_In_Touch.html

http://coala.io/coc

**Comment by satya-vinay** [comment]
Can I work on this?

**Comment by Makman2** [comment]
@satya-vinay you already have a newcomer issue assigned ;)

**Comment by prashantxc** [comment]
@Makman2 @jayvdb Can this be assigned to me? I am a newcomer.

**Comment by chhabrabhishek** [comment]
I want this newcomer issue to be assigned to me. Can I work on it?

**Comment by chhabrabhishek** [comment]
@jayvdb Hi! Do I have to give the COC reference of the coala website or do I give the direct reference of the github page?

**Comment by jayvdb** [comment]
COC on the website
