### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by agrawalarpit14** [coala/documentation#573]
https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

Under second example of writing a Good Commit Message:

`Closes https://github.com/coala/coala/issues/7971` --> `Fixes https://github.com/coala/coala/issues/4018`

**Comment by blossomica** [comment]
@agrawalarpit14  - Good catch! I tried to make a fix for your issue.

**Comment by jayvdb** [comment]
@blossomica , I've invited you to join the org.  See  https://coala.io/newcomer

**Comment by blossomica** [comment]
@jayvdb - Thank you!

I thought that joining the org is for people interested in being long term contributors and I don't have the bandwidth for that right now, but I'll definitely take the time to look into what the document is saying in depth to understand what it entails.
