### ISSUE TITLE
Blogory

### ISSUE THREAD

**Issue by sils** [coala/documentation#6]
http://blogory.org/add-content
Think we should add coala or something more generic even.

**Comment by sils1297** [comment]
@sims1253 could you do this? I imagine this to be rather uick.

**Comment by sims1253** [comment]
where do you want to put coala? are we a framework?

**Comment by sils1297** [comment]
yeah

**Comment by jayvdb** [comment]
This issue is definitely in the wrong repo now, but lets do some analysis of it before moving it again.

**Comment by jayvdb** [comment]
Not sure how important this is.
If it is, re-open on meta, or something.
