### ISSUE TITLE
glob examples are way too verbose

### ISSUE THREAD

**Issue by sils** [coala/documentation#70]
http://docs.coala.io/en/latest/Users/Glob_Patterns.html I know those are used for doctesting but I think this is a good example of how this can be misused.

**Comment by Dawny33** [comment]
This is the updated link for the `Glob_Patterns` doc: http://docs.coala.io/en/latest/Users/Glob_Patterns.html

**Comment by aptrishu** [comment]
I would like to work on this issue.

**Comment by Adrianzatreanu** [comment]
assigned

**Comment by aptrishu** [comment]
Should I just remove some of the examples ? Its true there are so many examples for each glob regex (which are getting obvious by the end). So, it seems verbose.

**Comment by sils** [comment]
yes, just examples that help the user should be there
