### ISSUE TITLE
Writing good commits needs a really good abstract

### ISSUE THREAD

**Issue by sils** [coala/documentation#72]
http://coala-docs.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

some people won't read it all so I feel like a rather well written summary on top would help us

**Comment by yash-nisar** [comment]
@sils1297 The link seems to be broken.

**Comment by aptrishu** [comment]
I would like to be assigned.

**Comment by aptrishu** [comment]
Something like this ?

{Tag-file or module name/optional}: {Summarize the changes made in commit in less than 50 characters,should not end with a period, capitalize properly}  
{blank line}  
{commit body - should describe the commit properly in less than 70 characters, focus on what and why rather than how you did it.}  
{blank line}  
{Fixes/Closes "reference of the issue, URL" }  

Use Imperative mood in the commit messages.

**Comment by Makman2** [comment]
But that's not an abstract, that's just a reference :) Pack that into some sentences so we can put that directly below the title :)

**Comment by aptrishu** [comment]
But as the issue says some people won't go through the whole page, they'll just read the abstract so if I'll keep the abstract shorter than this then they won't get the commit structure. Can you show me how should I do this ? that would be of much help. :)

**Comment by Makman2** [comment]
Yeah short sentences, just some piece of "code" misses some context :)
Just a little bit introduction :+1:

**Comment by aptrishu** [comment]
I'm not getting it. Please show me like how should I do it ? I'm not seeing any way to keep it short.

**Comment by Makman2** [comment]
Nvm, push your commit(s), then we'll see :)

**Comment by Adrianzatreanu** [comment]
imo this takes like 5-10mins to read and its very carefully explained. im for closing this issue, we dont need a quick reference, it wont be that quick and to make sense :/

**Comment by sils** [comment]
IMO having like a checklist on top with the most common issues could help
us save some time. Like

- I have no space before colon
- I have exactly one space after it
- The word after the colon starts with an upper case letter
...

Then we could just write "read the f*** checklist" :)

**Comment by aptrishu** [comment]
So what should be format of the quick reference ?
Like 
a commit example at the top.
and then checklist ?
or what ?

**Comment by Makman2** [comment]
I'm also getting confused now. Not far below we have some quick reference, and a checklist directly on top breaks context imo. @sils could you elaborate?
