### ISSUE TITLE
Glob_Patterns.rst: link to .coafile options

### ISSUE THREAD

**Issue by sims1253** [coala/documentation#73]
Note says:

"Note

If you're looking for a negation pattern to exclude paths, check out the --ignore argument or ignore .coafile option!"

Make it link to that option

**Comment by yash-nisar** [comment]
@sims1253 Could you please explain 

> Make it link to that option

**Comment by sims1253** [comment]
the doc has a chapter or section on the --ignore thing. The note should include a link to that section of the docs so a user does not have to search for it (like I had to)

**Comment by yash-nisar** [comment]
Alright, I can do this @sims1253 . :smile:

**Comment by yash-nisar** [comment]
Can I try this @Adrianzatreanu ?
